### ISSUE TITLE
colour is lost on wrapped lines

### ISSUE THREAD

**Issue by ashak** [c-hudson/muddler#4]
Colour is lost when lines are wrapped in the output, everything in this example should be the cyan colour

![image](https://github.com/user-attachments/assets/c98533a7-6da8-4516-993d-9d5ef2b02173)

If I expand the window so that it doesn't wrap, all the output is coloured as I expect it to be

**Comment by c-hudson** [comment]
Fixed. Ansi_substr() was handling the color state but not activating it at the beginning of the new string. Merged.
